databases:
  - name: postgres-db
    databaseName: smartnews
    user: django
    plan: free

# 2. All services (Redis, Web, Workers)
services:
  # 2a. The Redis Instance (for Celery)
  - type: worker  # <-- FIX 1: Change 'pserv' to 'worker'
    name: redis-broker
    image:
      url: redis:latest
    plan: free
    startCommand: "redis-server" # <-- FIX 2: Add the image's start command

  # 2b. The Django Web Service (Gunicorn)
  - type: web
    name: smartnews-web
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "gunicorn smartnews.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379 # This part is correct
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5

  # 2c. The Celery Worker (Runs the tasks)
  - type: worker
    name: smartnews-worker
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "celery -A smartnews worker --loglevel=info -P gevent"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379
      - key: SECRET_KEY
        fromService:
          type: web
          name: smartnews-web
          envVarKey: SECRET_KEY
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5

  # 2d. The Celery Beat Scheduler (Triggers the 4-hour task)
  - type: worker
    name: smartnews-beat
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "celery -A smartnews beat --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379
      - key: SECRET_KEY
        fromService:
          type: web
          name: smartnews-web
          envVarKey: SECRET_KEY
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5
