services:
  - type: db
    name: postgres-db
    databaseName: smartnews
    dbUser: django
    plan: free

  - type: pserv
    name: redis-broker
    image: redis
    plan: free

  - type: web
    name: smartnews-web
    env: python
    plan: free
    buildCommand: .build.sh
    startCommand: gunicorn smartnews.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-broker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: NEWSAPI_KEY
        sync: false   # You must add this manually in Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.9   # Match your Python version

  - type: worker
    name: smartnews-worker
    env: python
    plan: free
    buildCommand: .build.sh
    startCommand: celery -A smartnews worker --loglevel=info -P gevent
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-broker
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: smartnews-web
          envVarKey: SECRET_KEY
      - key: NEWSAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: worker
    name: smartnews-beat
    env: python
    plan: free
    buildCommand: .build.sh
    startCommand: celery -A smartnews beat --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-broker
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: smartnews-web
          envVarKey: SECRET_KEY
      - key: NEWSAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
