databases:
  - name: postgres-db
    databaseName: smartnews
    user: django
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all internal connections

services:
  - type: pserv
    name: redis-broker
    env: docker
    plan: free
    image:
      url: redis:latest

  - type: web
    name: smartnews-web
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "gunicorn smartnews.wsgi:application"
    dependsOn:
      - name: postgres-db
      - name: redis-broker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.5

  - type: worker
    name: smartnews-worker
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "celery -A smartnews worker --loglevel=info -P gevent"
    dependsOn:
      - name: smartnews-web
      - name: postgres-db
      - name: redis-broker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.5

  - type: worker
    name: smartnews-beat
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: "celery -A smartnews beat --loglevel=info"
    dependsOn:
      - name: smartnews-web
      - name: postgres-db
      - name: redis-broker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-broker:6379
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.5
